<?php

namespace App;

enum TaskType
{
    case CONFIGURE_ETHERNET_INTERFACE;
    case UPDATE_SYSTEM_INFO;
    case CONFIGURE_LAG_INTERFACE;
    case CONFIGURE_VLAN_INTERFACE;
    case CONFIGURE_ALL_INTERFACE;
    case ASSOCIATE_DEVICE_TO_SITE;
    case PREPROVISION_DEVICE_TO_GROUP;
    case TEST_TASK;
}
