<?php

namespace App;

enum TaskType
{
    case CONFIGURE_ETHERNET_INTERFACE;
    case UPDATE_SYSTEM_INFO;
    case CONFIGURE_LAG_INTERFACE;
    case CONFIGURE_VLAN_INTERFACE;
    case CREATE_VSF_PROFILE;
    case REMOVE_VSF_PROFILE_LOCAL_OVERRIDES;
    case ASSOCIATE_DEVICE_TO_SITE;
    case ASSOCIATE_SITE_AND_NAME;
    case PREPROVISION_DEVICE_TO_GROUP;
    case MOVE_DEVICE_TO_GROUP;
    case ASSIGN_DEVICE_FUNCTION;
    case TEST_TASK;
}
