<?php

namespace App;

enum TaskType
{
    case CONFIGURE_ALL_INTERFACE;
    case CONFIGURE_ETHERNET_INTERFACE;
    case UPDATE_SYSTEM_INFO;
    case CONFIGURE_LAG_INTERFACE;
    case CONFIGURE_VLAN_INTERFACE;
    case CONFIGURE_MIRROR_SESSION;
    case CREATE_VSF_PROFILE;
    case CREATE_VSX_PROFILE;
    case REMOVE_VSF_PROFILE_LOCAL_OVERRIDES;
    case ASSOCIATE_DEVICE_TO_SITE;
    case ASSOCIATE_SITE_AND_NAME;
    case PREPROVISION_DEVICE_TO_GROUP;
    case MOVE_DEVICE_TO_GROUP;
    case ASSIGN_DEVICE_FUNCTION;
    case ADD_VLANS_TO_DEVICE_GROUP;
    case RELAUNCH_FAILED_CRITICAL_CONFIG;
    case ASSIGN_SUBSCRIPTION;
    case UNASSIGN_SUBSCRIPTION;
    case ADD_DEVICES_TO_GREENLAKE_INVENTORY;
}
