const SAMPLE_DEVICE_HEADERS = [
    'name',
    'serial',
    'device_function',
    'description',
    'interface',
    'port_list',
    'ip_address',
    'vrf_forwarding',
    'sku',
    'site',
    'group',
    'port_profile',
    'interface_mode',
    'access_vlan',
    'native_vlan',
    'trunk_vlan_all',
    'trunk_vlan_ranges',
    'admin_edge_port',
    'admin_edge_port_trunk',
    'bpdu_guard',
    'loop_guard',
    'shutdown_on_split',
    'lacp_mode',
    'lacp_rate',
    'trunk_type',
    'vsx_profile',
    'vsx_role',
    'vsx_system_mac',
    'vsx_isl_ports',
    'vsx_keepalive_ports',
    'mirror_session_id',
    'mirror_dst_ports',
    'mirror_vlans',
    'mirror_name',
    'license_tag',
    'license_type',
] as const;

type SampleDeviceRow = Partial<
    Record<(typeof SAMPLE_DEVICE_HEADERS)[number], string>
>;

const SAMPLE_DEVICE_ROWS: SampleDeviceRow[] = [
    {
        name: 'Example Campus AP',
        serial: 'SN0000000001',
        device_function: 'CAMPUS_AP',
        site: 'Example Campus',
    },
    {
        name: 'Example Access Switch 1',
        serial: 'SN0000000002',
        device_function: 'ACCESS_SWITCH',
        description: 'data port VLAN 10',
        interface: '1/1/1-1/1/48',
        site: 'Building-A',
        port_profile: 'User-Access',
        interface_mode: 'ACCESS',
        access_vlan: '10',
        admin_edge_port: 'true',
        bpdu_guard: 'true',
        loop_guard: 'true',
    },
    {
        name: 'Example Access Switch 1',
        serial: 'SN0000000002',
        device_function: 'ACCESS_SWITCH',
        description: 'to Core Switch',
        interface: '1/1/51-1/1/52',
        site: 'Building-A',
        interface_mode: 'TRUNK',
        native_vlan: '10',
        trunk_vlan_ranges: '8&10-20',
        admin_edge_port_trunk: 'true',
        shutdown_on_split: 'true',
        lacp_mode: 'ACTIVE',
        lacp_rate: 'FAST',
    },
    {
        name: 'Example Access Switch 2',
        serial: 'SN0000000003',
        device_function: 'ACCESS_SWITCH',
        interface: '1/1/1&1/1/6-1/1/48',
        site: 'Building-A',
        interface_mode: 'ACCESS',
        access_vlan: '20',
    },
    {
        name: 'Example Access Switch 3',
        serial: 'SN0000000004',
        device_function: 'ACCESS_SWITCH',
        interface: '5',
        port_list: '1/1/14-1/1/15',
        site: 'Building-A',
        interface_mode: 'TRUNK',
        native_vlan: '10',
        trunk_vlan_all: 'true',
        lacp_mode: 'ACTIVE',
        lacp_rate: 'FAST',
        trunk_type: 'LACP',
    },
    {
        name: 'Example L3 Switch',
        serial: 'SN0000000005',
        device_function: 'ACCESS_SWITCH',
        interface: '11',
        ip_address: '192.168.11.1/24',
        site: 'Core-Site',
    },
    {
        name: 'Example Access Switch 1',
        serial: 'SN0000000002',
        device_function: 'ACCESS_SWITCH',
        description: 'routed uplink',
        interface: '1/1/53',
        ip_address: '10.255.0.1/30',
        vrf_forwarding: 'default',
        site: 'Building-A',
    },
    {
        name: 'Example Stack Conductor',
        serial: 'SN0000000006',
        device_function: 'ACCESS_SWITCH',
        interface: '1/1/49',
        sku: 'JL679A',
        site: 'Data Center',
    },
    {
        name: 'Example Stack Conductor',
        serial: 'SN0000000007',
        device_function: 'ACCESS_SWITCH',
        description: 'stack member switch',
        site: 'Core-Site',
    },
    {
        name: 'Example Branch Switch',
        serial: 'SN0000000008',
        device_function: 'ACCESS_SWITCH',
        site: 'Branch-HQ',
    },
    {
        name: 'Example New Switch',
        serial: 'SN0000000009',
        device_function: 'ACCESS_SWITCH',
        group: 'Onboarding-Pool',
    },
    {
        name: 'Example Core Switch',
        serial: 'SN0000000010',
        device_function: 'CORE_SWITCH',
    },
    {
        name: 'Example MDF-CORE-SW1',
        serial: 'SN0000000011',
        device_function: 'CORE_SWITCH',
        group: 'WHSE-TEST-CORE',
        site: 'Data Center',
        vsx_profile: 'vsx-core-pair-1',
        vsx_role: 'VSX_PRIMARY',
        vsx_system_mac: '02:00:00:00:00:01',
    },
    {
        name: 'Example MDF-CORE-SW2',
        serial: 'SN0000000012',
        device_function: 'CORE_SWITCH',
        group: 'WHSE-TEST-CORE',
        site: 'Data Center',
        vsx_profile: 'vsx-core-pair-1',
        vsx_role: 'VSX_SECONDARY',
        vsx_system_mac: '02:00:00:00:00:01',
    },
    {
        name: 'Example MDF-SVR-SW1',
        serial: 'SN0000000013',
        device_function: 'ACCESS_SWITCH',
        group: 'WHSE-TEST-ACCESS',
        site: 'Data Center',
        vsx_profile: 'vsx-svr-pair-1',
        vsx_role: 'VSX_PRIMARY',
        vsx_system_mac: '02:00:00:00:00:02',
    },
    {
        name: 'Example MDF-SVR-SW2',
        serial: 'SN0000000014',
        device_function: 'ACCESS_SWITCH',
        group: 'WHSE-TEST-ACCESS',
        site: 'Data Center',
        vsx_profile: 'vsx-svr-pair-1',
        vsx_role: 'VSX_SECONDARY',
        vsx_system_mac: '02:00:00:00:00:02',
    },
    {
        name: 'Example Custom VSX Switch 1',
        serial: 'SN0000000015',
        device_function: 'ACCESS_SWITCH',
        group: 'WHSE-TEST-ACCESS',
        site: 'Branch-HQ',
        vsx_profile: 'vsx-custom-pair-1',
        vsx_role: 'VSX_PRIMARY',
        vsx_system_mac: '02:00:00:00:00:03',
        vsx_isl_ports: '1/1/45-1/1/46',
        vsx_keepalive_ports: '1/1/47-1/1/48',
    },
    {
        name: 'Example Custom VSX Switch 2',
        serial: 'SN0000000016',
        device_function: 'ACCESS_SWITCH',
        group: 'WHSE-TEST-ACCESS',
        site: 'Branch-HQ',
        vsx_profile: 'vsx-custom-pair-1',
        vsx_role: 'VSX_SECONDARY',
        vsx_system_mac: '02:00:00:00:00:03',
        vsx_isl_ports: '1/1/45-1/1/46',
        vsx_keepalive_ports: '1/1/47-1/1/48',
    },
];

export function buildSampleDeviceCsv(): string {
    const lines = [
        SAMPLE_DEVICE_HEADERS.join(','),
        ...SAMPLE_DEVICE_ROWS.map((row) =>
            SAMPLE_DEVICE_HEADERS.map((h) => row[h] ?? '').join(','),
        ),
    ];
    return `\uFEFF${lines.join('\n')}`;
}

export function downloadSampleDeviceCsv(): void {
    const blob = new Blob([buildSampleDeviceCsv()], {
        type: 'text/csv;charset=utf-8;',
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'sample-device-configuration.csv';
    anchor.rel = 'noopener';
    anchor.click();
    URL.revokeObjectURL(url);
}
